solution: Plugins.sln

language: csharp
sudo: false
dist: trusty
dotnet: 1.0.4
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

install:
  - dotnet restore Plugins.sln

script:
  - dotnet build /p:Configuration=Release Plugins.sln
  - cd test/Limo.Plugins.Test && dotnet test /p:Configuration=Release 
